### PR TITLE
Added log scale option

### PR DESCRIPTION
**Pull request by OhadNir9**

### CODE REVIEW

**Comment by OhadNir9** [comment]
Solves #94

**Comment by OhadNir9** [comment]
Still have some too-many-arguments errors. For your consideration if we should ignore or reformat @saroad2 .

**Comment by saroad2** [comment]
Hey @OhadNir9 , excellent work!
Fixed some small things, but nothing too big.

Pay attention that I removed the usage of `FuncFormatter`. The reason for that is that we want *Eddington* to rely on *matplotlib* as much as possible. if there's something we can avoid implementing ourselves, we should not implement it. *matplotlib* has its own way of displaying log scale, so we should use it instead of inventing our own.

**Comment by OhadNir9** [comment]
@saroad2 Agree, but there was some problems with viewing the logscales properly in Eddington-GUI. That's the reason the FuncFormatter is there.
I did the PR in the GUI repo so you can take a look (61)

**Comment by saroad2** [comment]
NP, I'll take a look at it.

As a general note, *Eddington-GUI* should **never** affect the Eddington library's behavior (how things are displayed or calculated), only the other way around. The only thing it should have an effect on is the **API**, for the only reason that if *Eddington-GUI* cannot use the API properly, it probably means that other tools could not use this API because it is not agile enough.

The reason for the display problem is probably due to a BeeWare bug in Window's `Canvas` implementation. We should probably open an issue about that in *Eddington-GUI* and start working on a fix in *Toga*

**Pull request merged**
